# Generated by Django 4.2.1 on 2023-06-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('recuperarContraseña', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuperarcontraseña',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
