# Generated by Django 4.2.1 on 2023-06-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraseña', models.CharField(max_length=128)),
                ('fechaAlta', models.DateField(auto_now_add=True)),
                ('nombreDeUsuario', models.CharField(max_length=50)),
                ('correoElectronico', models.EmailField(max_length=50)),
            ],
        ),
    ]
